GOOMBA = "g"
KOOPA = "k"
FLYING_KOOPA = "K"
RED_KOOPA = "r"
RED_FLYING_KOOPA = "R"
SPINY = "y"

CANNON = "*"
CANNON_BASE = "B"

FLOWER_TUBE = "T"

QUESTION_LEVEL_UP = "@"
BRICK_LEVEL_UP = "U"

HIDDEN_ONE_UP = "1"
BRICK_ONE_UP = "L"

AIR = '-'
MUSHROOM_STEM = '|'

MARIO_PATH_TOKEN = '€'

NON_BLOCKS = [
    AIR, MUSHROOM_STEM,
    GOOMBA, KOOPA, FLYING_KOOPA, RED_KOOPA, RED_FLYING_KOOPA, SPINY,
    MARIO_PATH_TOKEN
]

MARIO_TOKEN = "M"
FINISH_TOKEN = "F"
